### ISSUE TITLE
Render Breaks If The Long Text Are Emojis

### ISSUE THREAD

**Issue by ErickSumargo** [mataku/MiddleEllipsisText#1]
Hi @mataku,
First of all great library!

However I spot issue where the render is not properly worked for emoji case. The emoji is broken when rendered.
<img width="121" alt="Screen Shot 2023-01-31 at 10 20 32" src="https://user-images.githubusercontent.com/21278875/215654960-cc0fe563-ada5-47d4-8cf1-33a44a22796e.png">

**Comment by mataku** [comment]
Thanks for your report!

I may not have time this week to investigate, but I will look at it.

**Comment by mataku** [comment]
@ErickSumargo released as v0.0.3, but currently only basic emoji supports. Emoji with code points of 2 or more, such as country flag,  🧑‍🦰 (🧑 + 🦰) doesn't yet support. This is TODO 🙏

**Comment by ErickSumargo** [comment]
@mataku 
Thank you very much for the quick fix! 

Yeah it's fixed for my case now. Regarding other emoji case, I think it's better to raise another issue to escalate.
